-- Procedure de INSERT para CP1_ESTADO
CREATE OR REPLACE PROCEDURE INSERT_CP1_ESTADO (
    p_nome IN CP1_ESTADO.NOME%TYPE
)
AS
BEGIN
    INSERT INTO CP1_ESTADO (NOME)
    VALUES (p_nome);
    COMMIT;
END INSERT_CP1_ESTADO;
/

-- Procedure de UPDATE para CP1_ESTADO
CREATE OR REPLACE PROCEDURE UPDATE_CP1_ESTADO (
    p_id IN CP1_ESTADO.ID%TYPE,
    p_nome IN CP1_ESTADO.NOME%TYPE
)
AS
BEGIN
    UPDATE CP1_ESTADO
    SET NOME = p_nome
    WHERE ID = p_id;
    COMMIT;
END UPDATE_CP1_ESTADO;
/

-- Procedure de DELETE para CP1_ESTADO
CREATE OR REPLACE PROCEDURE DELETE_CP1_ESTADO (
    p_id IN CP1_ESTADO.ID%TYPE
)
AS
BEGIN
    DELETE FROM CP1_ESTADO
    WHERE ID = p_id;
    COMMIT;
END DELETE_CP1_ESTADO;
/

-- Procedure de INSERT para CP1_CIDADE
CREATE OR REPLACE PROCEDURE INSERT_CP1_CIDADE (
    p_nome IN CP1_CIDADE.NOME%TYPE,
    p_estado_id IN CP1_CIDADE.ESTADO_ID%TYPE
)
AS
BEGIN
    INSERT INTO CP1_CIDADE (NOME, ESTADO_ID)
    VALUES (p_nome, p_estado_id);
    COMMIT;
END INSERT_CP1_CIDADE;
/

-- Procedure de UPDATE para CP1_CIDADE
CREATE OR REPLACE PROCEDURE UPDATE_CP1_CIDADE (
    p_id IN CP1_CIDADE.ID%TYPE,
    p_nome IN CP1_CIDADE.NOME%TYPE,
    p_estado_id IN CP1_CIDADE.ESTADO_ID%TYPE
)
AS
BEGIN
    UPDATE CP1_CIDADE
    SET NOME = p_nome, ESTADO_ID = p_estado_id
    WHERE ID = p_id;
    COMMIT;
END UPDATE_CP1_CIDADE;
/

-- Procedure de DELETE para CP1_CIDADE
CREATE OR REPLACE PROCEDURE DELETE_CP1_CIDADE (
    p_id IN CP1_CIDADE.ID%TYPE
)
AS
BEGIN
    DELETE FROM CP1_CIDADE
    WHERE ID = p_id;
    COMMIT;
END DELETE_CP1_CIDADE;
/

-- Procedure de INSERT para CP1_ESTADO_CIVIL
CREATE OR REPLACE PROCEDURE INSERT_CP1_ESTADO_CIVIL (
    p_nome IN CP1_ESTADO_CIVIL.NOME%TYPE
)
AS
BEGIN
    INSERT INTO CP1_ESTADO_CIVIL (NOME)
    VALUES (p_nome);
    COMMIT;
END INSERT_CP1_ESTADO_CIVIL;
/

-- Procedure de UPDATE para CP1_ESTADO_CIVIL
CREATE OR REPLACE PROCEDURE UPDATE_CP1_ESTADO_CIVIL (
    p_id IN CP1_ESTADO_CIVIL.ID%TYPE,
    p_nome IN CP1_ESTADO_CIVIL.NOME%TYPE
)
AS
BEGIN
    UPDATE CP1_ESTADO_CIVIL
    SET NOME = p_nome
    WHERE ID = p_id;
    COMMIT;
END UPDATE_CP1_ESTADO_CIVIL;
/

-- Procedure de DELETE para CP1_ESTADO_CIVIL
CREATE OR REPLACE PROCEDURE DELETE_CP1_ESTADO_CIVIL (
    p_id IN CP1_ESTADO_CIVIL.ID%TYPE
)
AS
BEGIN
    DELETE FROM CP1_ESTADO_CIVIL
    WHERE ID = p_id;
    COMMIT;
END DELETE_CP1_ESTADO_CIVIL;
/

-- Procedure de INSERT para CP1_CONVENIO
CREATE OR REPLACE PROCEDURE INSERT_CP1_CONVENIO (
    p_nome IN CP1_CONVENIO.NOME%TYPE
)
AS
BEGIN
    INSERT INTO CP1_CONVENIO (NOME)
    VALUES (p_nome);
    COMMIT;
END INSERT_CP1_CONVENIO;
/

-- Procedure de UPDATE para CP1_CONVENIO
CREATE OR REPLACE PROCEDURE UPDATE_CP1_CONVENIO (
    p_id IN CP1_CONVENIO.ID%TYPE,
    p_nome IN CP1_CONVENIO.NOME%TYPE
)
AS
BEGIN
    UPDATE CP1_CONVENIO
    SET NOME = p_nome
    WHERE ID = p_id;
    COMMIT;
END UPDATE_CP1_CONVENIO;
/

-- Procedure de DELETE para CP1_CONVENIO
CREATE OR REPLACE PROCEDURE DELETE_CP1_CONVENIO (
    p_id IN CP1_CONVENIO.ID%TYPE
)
AS
BEGIN
    DELETE FROM CP1_CONVENIO
    WHERE ID = p_id;
    COMMIT;
END DELETE_CP1_CONVENIO;
/
